name: Build

on:
  push:
    branches-ignore:
      - publish-docs

jobs:

  build_java_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: "8"

    - name: Cache Coursier
      uses: actions/cache@v2.1.7
      with:
        path: ~/.cache/coursier
        key: ${{ runner.os }}-coursier-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
        restore-keys: |
          ${{ runner.os }}-coursier-

    - name: Cache Ivy
      uses: actions/cache@v2.1.7
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-ivy-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
        restore-keys: |
          ${{ runner.os }}-ivy-

    - name: Build Java Project
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        export CI_BRANCH="${GITHUB_REF#refs/heads/}"
        .github/workflows/sbt-build.sh 2.13.3
